In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('./data/train_points.csv')

data.head()

/home/voudy/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,time,v_l,q,n_tr,code_azs,first_prch,location,region,code,code1,type,id,date,sum_b,cur_points
0,06:06:52,0.00,1,2016,2530.0,01.01.16 06:07:39,10.0,453.5,02040000,138.0,5,21-8B0-19339,99.09,3.96,-3.96
1,08:19:43,8.23,0,2016,3214.0,01.01.16 08:17:29,10.0,457.5,01010121,126.0,7,21-8A1-16393,262.04,7.87,-7.87
2,22:23:52,16.33,0,2016,17227.0,12.05.15 11:51:52,5.0,458.0,01010121,126.0,7,21-8AG-1768,545.33,21.82,-21.82
3,15:03:25,12.63,0,2016,2369.0,01.01.16 12:56:06,5.0,454.0,01010131,128.0,7,21-8AN-4396,454.58,13.64,-13.64
4,08:17:14,0.91,0,2016,3214.0,01.01.16 08:17:29,10.0,457.5,01010121,126.0,7,21-8A1-1639,28.95,0.87,-0.87